// GENERATED by tool/extract_icons.dart from orbix-design-handoff/design/orbix.css — do not edit.
//
// Path opcodes: 0 = moveTo(x, y), 1 = lineTo(x, y),
//               2 = cubicTo(x1, y1, x2, y2, x3, y3), 3 = close.
// ignore_for_file: lines_longer_than_80_chars

part of 'ox_icons.dart';

/// The Orbix icon set — 78 icons on a 24 × 24 grid, from `.i-*` in orbix.css.
enum OxIcons {
  home(
    'home',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 3, 10.5, 1, 12, 3, 1, 21, 10.5], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 5, 9.5, 1, 5, 20, 2, 5, 20.552, 5.448, 21, 6, 21, 1, 10, 21, 1, 10, 15, 1, 14, 15, 1, 14, 21, 1, 18, 21, 2, 18.552, 21, 19, 20.552, 19, 20, 1, 19, 9.5], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
  ),
  live(
    'live',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 5.5, 6.5, 1, 18.5, 6.5, 2, 20.156, 6.5, 21.5, 7.844, 21.5, 9.5, 1, 21.5, 17.5, 2, 21.5, 19.156, 20.156, 20.5, 18.5, 20.5, 1, 5.5, 20.5, 2, 3.844, 20.5, 2.5, 19.156, 2.5, 17.5, 1, 2.5, 9.5, 2, 2.5, 7.844, 3.844, 6.5, 5.5, 6.5, 3], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 8, 2.5, 1, 12, 6.5, 1, 16, 2.5], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
  ),
  film(
    'film',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 6, 3, 1, 18, 3, 2, 19.656, 3, 21, 4.344, 21, 6, 1, 21, 18, 2, 21, 19.656, 19.656, 21, 18, 21, 1, 6, 21, 2, 4.344, 21, 3, 19.656, 3, 18, 1, 3, 6, 2, 3, 4.344, 4.344, 3, 6, 3, 3], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 7.5, 3, 1, 7.5, 21, 0, 16.5, 3, 1, 16.5, 21, 0, 3, 8, 1, 7.5, 8, 0, 3, 16, 1, 7.5, 16, 0, 16.5, 8, 1, 21, 8, 0, 16.5, 16, 1, 21, 16, 0, 3, 12, 1, 21, 12], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
  ),
  series(
    'series',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 5.5, 8.5, 1, 18.5, 8.5, 2, 19.88, 8.5, 21, 9.62, 21, 11, 1, 21, 18, 2, 21, 19.38, 19.88, 20.5, 18.5, 20.5, 1, 5.5, 20.5, 2, 4.12, 20.5, 3, 19.38, 3, 18, 1, 3, 11, 2, 3, 9.62, 4.12, 8.5, 5.5, 8.5, 3], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 5.5, 5.5, 1, 18.5, 5.5, 0, 8, 2.5, 1, 16, 2.5], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 10.5, 12, 1, 14.5, 14.5, 1, 10.5, 17, 3], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
  ),
  heart(
    'heart',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 12, 20.5, 2, 12, 20.5, 3.5, 15.7, 3.5, 9.5, 2, 3.472, 7.437, 4.822, 5.608, 6.802, 5.026, 2, 8.781, 4.443, 10.906, 5.25, 12, 7, 2, 13.094, 5.25, 15.219, 4.443, 17.198, 5.026, 2, 19.178, 5.608, 20.528, 7.437, 20.5, 9.5, 2, 20.5, 15.7, 12, 20.5, 12, 20.5, 3], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
  ),
  heartFill(
    'heart-fill',
    <OxIconOp>[
      OxIconOp.fill(<double>[0, 12, 20.5, 2, 12, 20.5, 3.5, 15.7, 3.5, 9.5, 2, 3.472, 7.437, 4.822, 5.608, 6.802, 5.026, 2, 8.781, 4.443, 10.906, 5.25, 12, 7, 2, 13.094, 5.25, 15.219, 4.443, 17.198, 5.026, 2, 19.178, 5.608, 20.528, 7.437, 20.5, 9.5, 2, 20.5, 15.7, 12, 20.5, 12, 20.5, 3]),
      OxIconOp.stroke(<double>[0, 12, 20.5, 2, 12, 20.5, 3.5, 15.7, 3.5, 9.5, 2, 3.472, 7.437, 4.822, 5.608, 6.802, 5.026, 2, 8.781, 4.443, 10.906, 5.25, 12, 7, 2, 13.094, 5.25, 15.219, 4.443, 17.198, 5.026, 2, 19.178, 5.608, 20.528, 7.437, 20.5, 9.5, 2, 20.5, 15.7, 12, 20.5, 12, 20.5, 3], width: 1.8, join: StrokeJoin.round),
    ],
  ),
  user(
    'user',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 12, 4, 2, 14.208, 4, 16, 5.792, 16, 8, 2, 16, 10.208, 14.208, 12, 12, 12, 2, 9.792, 12, 8, 10.208, 8, 8, 2, 8, 5.792, 9.792, 4, 12, 4, 3], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 4, 21, 2, 4, 17, 7.6, 14.5, 12, 14.5, 2, 16.4, 14.5, 20, 17, 20, 21], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
  ),
  userPlus(
    'user-plus',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 10, 4, 2, 12.208, 4, 14, 5.792, 14, 8, 2, 14, 10.208, 12.208, 12, 10, 12, 2, 7.792, 12, 6, 10.208, 6, 8, 2, 6, 5.792, 7.792, 4, 10, 4, 3], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 3, 21, 2, 3, 17, 6.1, 14.5, 10, 14.5, 2, 11.5, 14.5, 12.9, 14.9, 14, 15.5, 0, 19, 14, 1, 19, 20, 0, 16, 17, 1, 22, 17], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
  ),
  search(
    'search',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 11, 4, 2, 14.863, 4, 18, 7.137, 18, 11, 2, 18, 14.863, 14.863, 18, 11, 18, 2, 7.137, 18, 4, 14.863, 4, 11, 2, 4, 7.137, 7.137, 4, 11, 4, 3], width: 1.9, cap: StrokeCap.round, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 20, 20, 1, 16.4, 16.4], width: 1.9, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
  ),
  cast(
    'cast',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 3, 8, 1, 3, 6, 2, 3, 4.895, 3.895, 4, 5, 4, 1, 19, 4, 2, 20.105, 4, 21, 4.895, 21, 6, 1, 21, 18, 2, 21, 19.105, 20.105, 20, 19, 20, 1, 13, 20], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 3, 12, 2, 7.418, 12, 11, 15.582, 11, 20, 0, 3, 16, 2, 5.209, 16, 7, 17.791, 7, 20, 0, 3, 20, 1, 3.01, 20], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
  ),
  bell(
    'bell',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 6, 16, 1, 6, 11, 2, 6, 7.686, 8.686, 5, 12, 5, 2, 15.314, 5, 18, 7.686, 18, 11, 1, 18, 16, 1, 19.5, 18, 1, 4.5, 18, 3], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 10, 21, 1, 14, 21], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
  ),
  play(
    'play',
    <OxIconOp>[
      OxIconOp.fill(<double>[0, 7, 4.8, 1, 7, 19.2, 2, 7.002, 19.556, 7.194, 19.884, 7.503, 20.062, 2, 7.812, 20.239, 8.192, 20.238, 8.5, 20.06, 1, 20.5, 12.86, 2, 20.804, 12.68, 20.99, 12.353, 20.99, 12, 2, 20.99, 11.647, 20.804, 11.32, 20.5, 11.14, 1, 8.5, 3.94, 2, 8.192, 3.762, 7.812, 3.761, 7.503, 3.938, 2, 7.194, 4.116, 7.002, 4.444, 7, 4.8, 3]),
    ],
  ),
  pause(
    'pause',
    <OxIconOp>[
      OxIconOp.fill(<double>[0, 6.9, 4, 1, 8.6, 4, 2, 9.373, 4, 10, 4.627, 10, 5.4, 1, 10, 18.6, 2, 10, 19.373, 9.373, 20, 8.6, 20, 1, 6.9, 20, 2, 6.127, 20, 5.5, 19.373, 5.5, 18.6, 1, 5.5, 5.4, 2, 5.5, 4.627, 6.127, 4, 6.9, 4, 3]),
      OxIconOp.fill(<double>[0, 15.4, 4, 1, 17.1, 4, 2, 17.873, 4, 18.5, 4.627, 18.5, 5.4, 1, 18.5, 18.6, 2, 18.5, 19.373, 17.873, 20, 17.1, 20, 1, 15.4, 20, 2, 14.627, 20, 14, 19.373, 14, 18.6, 1, 14, 5.4, 2, 14, 4.627, 14.627, 4, 15.4, 4, 3]),
    ],
  ),
  plus(
    'plus',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 12, 5, 1, 12, 19, 0, 5, 12, 1, 19, 12], width: 2, cap: StrokeCap.round),
    ],
  ),
  info(
    'info',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 12, 3, 2, 16.967, 3, 21, 7.033, 21, 12, 2, 21, 16.967, 16.967, 21, 12, 21, 2, 7.033, 21, 3, 16.967, 3, 12, 2, 3, 7.033, 7.033, 3, 12, 3, 3], width: 1.8, cap: StrokeCap.round),
      OxIconOp.stroke(<double>[0, 12, 11, 1, 12, 16.5, 0, 12, 7.8, 1, 12.01, 7.8], width: 1.8, cap: StrokeCap.round),
    ],
  ),
  share(
    'share',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 12, 3, 1, 12, 15, 0, 7.5, 7.5, 1, 12, 3, 1, 16.5, 7.5], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 5, 12, 1, 5, 19, 2, 5, 20.105, 5.895, 21, 7, 21, 1, 17, 21, 2, 18.105, 21, 19, 20.105, 19, 19, 1, 19, 12], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
  ),
  settings(
    'settings',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 12, 9, 2, 13.656, 9, 15, 10.344, 15, 12, 2, 15, 13.656, 13.656, 15, 12, 15, 2, 10.344, 15, 9, 13.656, 9, 12, 2, 9, 10.344, 10.344, 9, 12, 9, 3], width: 1.7, cap: StrokeCap.round, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 19.4, 15, 2, 19.142, 15.607, 19.259, 16.309, 19.7, 16.8, 1, 19.8, 16.9, 2, 20.426, 17.37, 20.721, 18.161, 20.554, 18.926, 2, 20.388, 19.69, 19.79, 20.288, 19.026, 20.454, 2, 18.261, 20.621, 17.47, 20.326, 17, 19.7, 1, 16.9, 19.6, 2, 16.409, 19.159, 15.707, 19.042, 15.1, 19.3, 2, 14.507, 19.568, 14.119, 20.15, 14.1, 20.8, 1, 14.1, 21, 2, 14.1, 22.105, 13.205, 23, 12.1, 23, 2, 10.995, 23, 10.1, 22.105, 10.1, 21, 1, 10.1, 20.9, 2, 10.064, 20.226, 9.632, 19.637, 9, 19.4, 2, 8.393, 19.142, 7.691, 19.259, 7.2, 19.7, 1, 7.1, 19.8, 2, 6.63, 20.426, 5.839, 20.721, 5.074, 20.554, 2, 4.31, 20.388, 3.712, 19.79, 3.546, 19.026, 2, 3.379, 18.261, 3.674, 17.47, 4.3, 17, 1, 4.4, 16.9, 2, 4.841, 16.409, 4.958, 15.707, 4.7, 15.1, 2, 4.432, 14.507, 3.85, 14.119, 3.2, 14.1, 1, 3, 14.1, 2, 1.895, 14.1, 1, 13.205, 1, 12.1, 2, 1, 10.995, 1.895, 10.1, 3, 10.1, 1, 3.1, 10.1, 2, 3.774, 10.064, 4.363, 9.632, 4.6, 9, 2, 4.858, 8.393, 4.741, 7.691, 4.3, 7.2, 1, 4.2, 7.1, 2, 3.574, 6.63, 3.279, 5.839, 3.446, 5.074, 2, 3.612, 4.31, 4.21, 3.712, 4.974, 3.546, 2, 5.739, 3.379, 6.53, 3.674, 7, 4.3, 1, 7.1, 4.4, 2, 7.591, 4.841, 8.293, 4.958, 8.9, 4.7, 1, 9, 4.7, 2, 9.593, 4.432, 9.981, 3.85, 10, 3.2, 1, 10, 3, 2, 10, 1.895, 10.895, 1, 12, 1, 2, 13.105, 1, 14, 1.895, 14, 3, 1, 14, 3.1, 2, 14.019, 3.75, 14.407, 4.332, 15, 4.6, 2, 15.607, 4.858, 16.309, 4.741, 16.8, 4.3, 1, 16.9, 4.2, 2, 17.37, 3.574, 18.161, 3.279, 18.926, 3.446, 2, 19.69, 3.612, 20.288, 4.21, 20.454, 4.974, 2, 20.621, 5.739, 20.326, 6.53, 19.7, 7, 1, 19.6, 7.1, 2, 19.159, 7.591, 19.042, 8.293, 19.3, 8.9, 1, 19.3, 9, 2, 19.568, 9.593, 20.15, 9.981, 20.8, 10, 1, 21, 10, 2, 22.105, 10, 23, 10.895, 23, 12, 2, 23, 13.105, 22.105, 14, 21, 14, 1, 20.9, 14, 2, 20.25, 14.019, 19.668, 14.407, 19.4, 15, 3], width: 1.7, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
  ),
  chevR(
    'chev-r',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 9, 5, 1, 16, 12, 1, 9, 19], width: 2, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
    mirrorInRtl: true,
  ),
  chevL(
    'chev-l',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 15, 5, 1, 8, 12, 1, 15, 19], width: 2, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
    mirrorInRtl: true,
  ),
  chevD(
    'chev-d',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 5, 9, 1, 12, 16, 1, 19, 9], width: 2, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
  ),
  chevU(
    'chev-u',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 5, 15, 1, 12, 8, 1, 19, 15], width: 2, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
  ),
  back(
    'back',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 20, 12, 1, 4, 12, 0, 10, 6, 1, 4, 12, 1, 10, 18], width: 2, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
    mirrorInRtl: true,
  ),
  close(
    'close',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 6, 6, 1, 18, 18, 0, 18, 6, 1, 6, 18], width: 2, cap: StrokeCap.round),
    ],
  ),
  check(
    'check',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 4.5, 12.5, 1, 9.5, 17.5, 1, 19.5, 6.5], width: 2.2, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
  ),
  lock(
    'lock',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 7, 10.5, 1, 17, 10.5, 2, 18.38, 10.5, 19.5, 11.62, 19.5, 13, 1, 19.5, 18.5, 2, 19.5, 19.88, 18.38, 21, 17, 21, 1, 7, 21, 2, 5.62, 21, 4.5, 19.88, 4.5, 18.5, 1, 4.5, 13, 2, 4.5, 11.62, 5.62, 10.5, 7, 10.5, 3], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 8, 10.5, 1, 8, 7.5, 2, 8, 5.291, 9.791, 3.5, 12, 3.5, 2, 14.209, 3.5, 16, 5.291, 16, 7.5, 1, 16, 10.5, 0, 12, 14.5, 1, 12, 17], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
  ),
  unlock(
    'unlock',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 7, 10.5, 1, 17, 10.5, 2, 18.38, 10.5, 19.5, 11.62, 19.5, 13, 1, 19.5, 18.5, 2, 19.5, 19.88, 18.38, 21, 17, 21, 1, 7, 21, 2, 5.62, 21, 4.5, 19.88, 4.5, 18.5, 1, 4.5, 13, 2, 4.5, 11.62, 5.62, 10.5, 7, 10.5, 3], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 8, 10.5, 1, 8, 7.5, 2, 8.009, 5.593, 9.363, 3.958, 11.235, 3.594, 2, 13.107, 3.229, 14.976, 4.236, 15.7, 6], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
  ),
  grid(
    'grid',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 5.3, 3.5, 1, 8.7, 3.5, 2, 9.693, 3.5, 10.5, 4.307, 10.5, 5.3, 1, 10.5, 8.7, 2, 10.5, 9.693, 9.693, 10.5, 8.7, 10.5, 1, 5.3, 10.5, 2, 4.307, 10.5, 3.5, 9.693, 3.5, 8.7, 1, 3.5, 5.3, 2, 3.5, 4.307, 4.307, 3.5, 5.3, 3.5, 3], width: 1.8, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 15.3, 3.5, 1, 18.7, 3.5, 2, 19.693, 3.5, 20.5, 4.307, 20.5, 5.3, 1, 20.5, 8.7, 2, 20.5, 9.693, 19.693, 10.5, 18.7, 10.5, 1, 15.3, 10.5, 2, 14.307, 10.5, 13.5, 9.693, 13.5, 8.7, 1, 13.5, 5.3, 2, 13.5, 4.307, 14.307, 3.5, 15.3, 3.5, 3], width: 1.8, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 5.3, 13.5, 1, 8.7, 13.5, 2, 9.693, 13.5, 10.5, 14.307, 10.5, 15.3, 1, 10.5, 18.7, 2, 10.5, 19.693, 9.693, 20.5, 8.7, 20.5, 1, 5.3, 20.5, 2, 4.307, 20.5, 3.5, 19.693, 3.5, 18.7, 1, 3.5, 15.3, 2, 3.5, 14.307, 4.307, 13.5, 5.3, 13.5, 3], width: 1.8, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 15.3, 13.5, 1, 18.7, 13.5, 2, 19.693, 13.5, 20.5, 14.307, 20.5, 15.3, 1, 20.5, 18.7, 2, 20.5, 19.693, 19.693, 20.5, 18.7, 20.5, 1, 15.3, 20.5, 2, 14.307, 20.5, 13.5, 19.693, 13.5, 18.7, 1, 13.5, 15.3, 2, 13.5, 14.307, 14.307, 13.5, 15.3, 13.5, 3], width: 1.8, join: StrokeJoin.round),
    ],
  ),
  list(
    'list',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 9, 6, 1, 20, 6, 0, 9, 12, 1, 20, 12, 0, 9, 18, 1, 20, 18, 0, 4, 6, 1, 4.01, 6, 0, 4, 12, 1, 4.01, 12, 0, 4, 18, 1, 4.01, 18], width: 1.9, cap: StrokeCap.round),
    ],
  ),
  mic(
    'mic',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 12, 3, 1, 12, 3, 2, 13.656, 3, 15, 4.344, 15, 6, 1, 15, 11, 2, 15, 12.656, 13.656, 14, 12, 14, 1, 12, 14, 2, 10.344, 14, 9, 12.656, 9, 11, 1, 9, 6, 2, 9, 4.344, 10.344, 3, 12, 3, 3], width: 1.8, cap: StrokeCap.round),
      OxIconOp.stroke(<double>[0, 5.5, 11, 2, 5.5, 14.59, 8.41, 17.5, 12, 17.5, 2, 15.59, 17.5, 18.5, 14.59, 18.5, 11, 0, 12, 17.5, 1, 12, 21], width: 1.8, cap: StrokeCap.round),
    ],
  ),
  filter(
    'filter',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 4, 6, 1, 14, 6, 0, 18, 6, 1, 20, 6, 0, 4, 12, 1, 8, 12, 0, 12, 12, 1, 20, 12, 0, 4, 18, 1, 16, 18], width: 1.8, cap: StrokeCap.round),
      OxIconOp.stroke(<double>[0, 16, 4, 2, 17.104, 4, 18, 4.896, 18, 6, 2, 18, 7.104, 17.104, 8, 16, 8, 2, 14.896, 8, 14, 7.104, 14, 6, 2, 14, 4.896, 14.896, 4, 16, 4, 3], width: 1.8, cap: StrokeCap.round),
      OxIconOp.stroke(<double>[0, 10, 10, 2, 11.104, 10, 12, 10.896, 12, 12, 2, 12, 13.104, 11.104, 14, 10, 14, 2, 8.896, 14, 8, 13.104, 8, 12, 2, 8, 10.896, 8.896, 10, 10, 10, 3], width: 1.8, cap: StrokeCap.round),
      OxIconOp.stroke(<double>[0, 18, 16, 2, 19.104, 16, 20, 16.896, 20, 18, 2, 20, 19.104, 19.104, 20, 18, 20, 2, 16.896, 20, 16, 19.104, 16, 18, 2, 16, 16.896, 16.896, 16, 18, 16, 3], width: 1.8, cap: StrokeCap.round),
    ],
  ),
  star(
    'star',
    <OxIconOp>[
      OxIconOp.fill(<double>[0, 12, 2.8, 1, 14.8, 8.6, 1, 21.1, 9.5, 1, 16.5, 13.9, 1, 17.6, 20.2, 1, 12, 17.2, 1, 6.4, 20.2, 1, 7.5, 13.9, 1, 2.9, 9.5, 1, 9.2, 8.6, 3]),
    ],
  ),
  clock(
    'clock',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 12, 3, 2, 16.967, 3, 21, 7.033, 21, 12, 2, 21, 16.967, 16.967, 21, 12, 21, 2, 7.033, 21, 3, 16.967, 3, 12, 2, 3, 7.033, 7.033, 3, 12, 3, 3], width: 1.8, cap: StrokeCap.round),
      OxIconOp.stroke(<double>[0, 12, 7, 1, 12, 12, 1, 15, 14], width: 1.8, cap: StrokeCap.round),
    ],
  ),
  calendar(
    'calendar',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 6, 5, 1, 18, 5, 2, 19.38, 5, 20.5, 6.12, 20.5, 7.5, 1, 20.5, 18, 2, 20.5, 19.38, 19.38, 20.5, 18, 20.5, 1, 6, 20.5, 2, 4.62, 20.5, 3.5, 19.38, 3.5, 18, 1, 3.5, 7.5, 2, 3.5, 6.12, 4.62, 5, 6, 5, 3], width: 1.8, cap: StrokeCap.round),
      OxIconOp.stroke(<double>[0, 3.5, 10, 1, 20.5, 10, 0, 8, 3, 1, 8, 7, 0, 16, 3, 1, 16, 7], width: 1.8, cap: StrokeCap.round),
    ],
  ),
  globe(
    'globe',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 12, 3, 2, 16.967, 3, 21, 7.033, 21, 12, 2, 21, 16.967, 16.967, 21, 12, 21, 2, 7.033, 21, 3, 16.967, 3, 12, 2, 3, 7.033, 7.033, 3, 12, 3, 3], width: 1.7, cap: StrokeCap.round),
      OxIconOp.stroke(<double>[0, 3, 12, 1, 21, 12, 0, 12, 3, 2, 14.5, 5.6, 15.8, 8.6, 15.8, 12, 2, 15.8, 15.4, 14.5, 18.4, 12, 21, 2, 9.5, 18.4, 8.2, 15.4, 8.2, 12, 2, 8.2, 8.6, 9.5, 5.6, 12, 3, 3], width: 1.7, cap: StrokeCap.round),
    ],
  ),
  volume(
    'volume',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 4, 9.5, 1, 4, 14.5, 1, 7.5, 14.5, 1, 12, 18.5, 1, 12, 5.5, 1, 7.5, 9.5, 3], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 15.5, 9, 2, 16.361, 9.759, 16.854, 10.852, 16.854, 12, 2, 16.854, 13.148, 16.361, 14.241, 15.5, 15, 0, 18, 6.5, 2, 19.531, 7.919, 20.401, 9.912, 20.401, 12, 2, 20.401, 14.088, 19.531, 16.081, 18, 17.5], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
  ),
  sun(
    'sun',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 12, 8, 2, 14.208, 8, 16, 9.792, 16, 12, 2, 16, 14.208, 14.208, 16, 12, 16, 2, 9.792, 16, 8, 14.208, 8, 12, 2, 8, 9.792, 9.792, 8, 12, 8, 3], width: 1.8, cap: StrokeCap.round),
      OxIconOp.stroke(<double>[0, 12, 2.5, 1, 12, 4.5, 0, 12, 19.5, 1, 12, 21.5, 0, 2.5, 12, 1, 4.5, 12, 0, 19.5, 12, 1, 21.5, 12, 0, 5.3, 5.3, 1, 6.7, 6.7, 0, 17.3, 17.3, 1, 18.7, 18.7, 0, 5.3, 18.7, 1, 6.7, 17.3, 0, 17.3, 6.7, 1, 18.7, 5.3], width: 1.8, cap: StrokeCap.round),
    ],
  ),
  moon(
    'moon',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 20, 14.5, 2, 18.586, 17.809, 15.136, 19.767, 11.57, 19.284, 2, 8.004, 18.801, 5.199, 15.996, 4.716, 12.43, 2, 4.233, 8.864, 6.191, 5.414, 9.5, 4, 2, 6.601, 6.899, 6.601, 11.601, 9.5, 14.5, 2, 12.399, 17.399, 17.101, 17.399, 20, 14.5, 3], width: 1.8, join: StrokeJoin.round),
    ],
  ),
  aspect(
    'aspect',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 5, 5, 1, 19, 5, 2, 20.38, 5, 21.5, 6.12, 21.5, 7.5, 1, 21.5, 16.5, 2, 21.5, 17.88, 20.38, 19, 19, 19, 1, 5, 19, 2, 3.62, 19, 2.5, 17.88, 2.5, 16.5, 1, 2.5, 7.5, 2, 2.5, 6.12, 3.62, 5, 5, 5, 3], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 6, 11.5, 1, 6, 8.5, 1, 9.5, 8.5, 0, 18, 12.5, 1, 18, 15.5, 1, 14.5, 15.5], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
  ),
  rotate(
    'rotate',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 9, 2.5, 1, 15, 2.5, 2, 16.104, 2.5, 17, 3.396, 17, 4.5, 1, 17, 15.5, 2, 17, 16.604, 16.104, 17.5, 15, 17.5, 1, 9, 17.5, 2, 7.896, 17.5, 7, 16.604, 7, 15.5, 1, 7, 4.5, 2, 7, 3.396, 7.896, 2.5, 9, 2.5, 3], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 3, 14, 2, 3.541, 17.715, 6.331, 20.705, 10, 21.5, 0, 21, 10, 2, 20.691, 7.867, 19.626, 5.915, 18, 4.5], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 7.5, 21.5, 1, 10.5, 21.5, 1, 10.5, 18.5], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
  ),
  fullscreen(
    'fullscreen',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 4, 9, 1, 4, 4, 1, 9, 4, 0, 20, 9, 1, 20, 4, 1, 15, 4, 0, 4, 15, 1, 4, 20, 1, 9, 20, 0, 20, 15, 1, 20, 20, 1, 15, 20], width: 1.9, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
  ),
  pip(
    'pip',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 5, 4.5, 1, 19, 4.5, 2, 20.38, 4.5, 21.5, 5.62, 21.5, 7, 1, 21.5, 17, 2, 21.5, 18.38, 20.38, 19.5, 19, 19.5, 1, 5, 19.5, 2, 3.62, 19.5, 2.5, 18.38, 2.5, 17, 1, 2.5, 7, 2, 2.5, 5.62, 3.62, 4.5, 5, 4.5, 3], width: 1.8, join: StrokeJoin.round),
      OxIconOp.fill(<double>[0, 13.2, 11, 1, 17.8, 11, 2, 18.462, 11, 19, 11.538, 19, 12.2, 1, 19, 15.8, 2, 19, 16.462, 18.462, 17, 17.8, 17, 1, 13.2, 17, 2, 12.538, 17, 12, 16.462, 12, 15.8, 1, 12, 12.2, 2, 12, 11.538, 12.538, 11, 13.2, 11, 3]),
      OxIconOp.stroke(<double>[0, 13.2, 11, 1, 17.8, 11, 2, 18.462, 11, 19, 11.538, 19, 12.2, 1, 19, 15.8, 2, 19, 16.462, 18.462, 17, 17.8, 17, 1, 13.2, 17, 2, 12.538, 17, 12, 16.462, 12, 15.8, 1, 12, 12.2, 2, 12, 11.538, 12.538, 11, 13.2, 11, 3], width: 1.8, join: StrokeJoin.round),
    ],
  ),
  cc(
    'cc',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 5, 5, 1, 19, 5, 2, 20.38, 5, 21.5, 6.12, 21.5, 7.5, 1, 21.5, 16.5, 2, 21.5, 17.88, 20.38, 19, 19, 19, 1, 5, 19, 2, 3.62, 19, 2.5, 17.88, 2.5, 16.5, 1, 2.5, 7.5, 2, 2.5, 6.12, 3.62, 5, 5, 5, 3], width: 1.8, cap: StrokeCap.round),
      OxIconOp.stroke(<double>[0, 10.5, 10.2, 2, 9.515, 9.25, 7.948, 9.269, 6.986, 10.243, 2, 6.025, 11.217, 6.025, 12.783, 6.986, 13.757, 2, 7.948, 14.731, 9.515, 14.75, 10.5, 13.8, 0, 17.5, 10.2, 2, 16.515, 9.25, 14.948, 9.269, 13.986, 10.243, 2, 13.025, 11.217, 13.025, 12.783, 13.986, 13.757, 2, 14.948, 14.731, 16.515, 14.75, 17.5, 13.8], width: 1.8, cap: StrokeCap.round),
    ],
  ),
  audio(
    'audio',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 4, 10, 1, 4, 14, 0, 8, 7, 1, 8, 17, 0, 12, 4, 1, 12, 20, 0, 16, 8, 1, 16, 16, 0, 20, 11, 1, 20, 13], width: 1.9, cap: StrokeCap.round),
    ],
  ),
  speed(
    'speed',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 4.5, 17, 2, 2.593, 13.424, 3.476, 8.998, 6.61, 6.428, 2, 9.744, 3.857, 14.256, 3.857, 17.39, 6.428, 2, 20.524, 8.998, 21.407, 13.424, 19.5, 17], width: 1.8, cap: StrokeCap.round),
      OxIconOp.stroke(<double>[0, 12, 13, 1, 16, 9], width: 1.8, cap: StrokeCap.round),
      OxIconOp.fill(<double>[0, 12, 11.8, 2, 12.662, 11.8, 13.2, 12.338, 13.2, 13, 2, 13.2, 13.662, 12.662, 14.2, 12, 14.2, 2, 11.338, 14.2, 10.8, 13.662, 10.8, 13, 2, 10.8, 12.338, 11.338, 11.8, 12, 11.8, 3]),
      OxIconOp.stroke(<double>[0, 12, 11.8, 2, 12.662, 11.8, 13.2, 12.338, 13.2, 13, 2, 13.2, 13.662, 12.662, 14.2, 12, 14.2, 2, 11.338, 14.2, 10.8, 13.662, 10.8, 13, 2, 10.8, 12.338, 11.338, 11.8, 12, 11.8, 3], width: 1.8, cap: StrokeCap.round),
    ],
  ),
  hd(
    'hd',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 5, 5, 1, 19, 5, 2, 20.38, 5, 21.5, 6.12, 21.5, 7.5, 1, 21.5, 16.5, 2, 21.5, 17.88, 20.38, 19, 19, 19, 1, 5, 19, 2, 3.62, 19, 2.5, 17.88, 2.5, 16.5, 1, 2.5, 7.5, 2, 2.5, 6.12, 3.62, 5, 5, 5, 3], width: 1.7, cap: StrokeCap.round, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 7, 9, 1, 7, 15, 0, 7, 12, 1, 10.5, 12, 0, 10.5, 9, 1, 10.5, 15, 0, 14, 9, 1, 14, 15, 1, 15.4, 15, 2, 16.836, 15, 18, 13.836, 18, 12.4, 1, 18, 11.6, 2, 18, 10.164, 16.836, 9, 15.4, 9, 3], width: 1.7, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
  ),
  prev(
    'prev',
    <OxIconOp>[
      OxIconOp.fill(<double>[0, 5.6, 5, 1, 6, 5, 2, 6.607, 5, 7.1, 5.493, 7.1, 6.1, 1, 7.1, 17.9, 2, 7.1, 18.507, 6.607, 19, 6, 19, 1, 5.6, 19, 2, 4.993, 19, 4.5, 18.507, 4.5, 17.9, 1, 4.5, 6.1, 2, 4.5, 5.493, 4.993, 5, 5.6, 5, 3]),
      OxIconOp.fill(<double>[0, 19.5, 6.2, 1, 19.5, 17.8, 2, 19.5, 18.179, 19.286, 18.525, 18.947, 18.694, 2, 18.608, 18.864, 18.203, 18.827, 17.9, 18.6, 1, 9.3, 12.8, 2, 9.048, 12.611, 8.9, 12.315, 8.9, 12, 2, 8.9, 11.685, 9.048, 11.389, 9.3, 11.2, 1, 17.9, 5.4, 2, 18.203, 5.173, 18.608, 5.136, 18.947, 5.306, 2, 19.286, 5.475, 19.5, 5.821, 19.5, 6.2, 3]),
    ],
  ),
  next(
    'next',
    <OxIconOp>[
      OxIconOp.fill(<double>[0, 18, 5, 1, 18.4, 5, 2, 19.007, 5, 19.5, 5.493, 19.5, 6.1, 1, 19.5, 17.9, 2, 19.5, 18.507, 19.007, 19, 18.4, 19, 1, 18, 19, 2, 17.393, 19, 16.9, 18.507, 16.9, 17.9, 1, 16.9, 6.1, 2, 16.9, 5.493, 17.393, 5, 18, 5, 3]),
      OxIconOp.fill(<double>[0, 4.5, 6.2, 1, 4.5, 17.8, 2, 4.5, 18.179, 4.714, 18.525, 5.053, 18.694, 2, 5.392, 18.864, 5.797, 18.827, 6.1, 18.6, 1, 14.7, 12.8, 2, 14.952, 12.611, 15.1, 12.315, 15.1, 12, 2, 15.1, 11.685, 14.952, 11.389, 14.7, 11.2, 1, 6.1, 5.4, 2, 5.797, 5.173, 5.392, 5.136, 5.053, 5.306, 2, 4.714, 5.475, 4.5, 5.821, 4.5, 6.2, 3]),
    ],
  ),
  rew(
    'rew',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 4, 12, 2, 3.994, 15.81, 6.676, 19.096, 10.41, 19.854, 2, 14.144, 20.611, 17.894, 18.629, 19.373, 15.118, 2, 20.852, 11.606, 19.648, 7.539, 16.497, 5.397, 2, 13.346, 3.255, 9.121, 3.633, 6.4, 6.3, 1, 4, 8.5], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 4, 3.5, 1, 4, 8.5, 1, 9, 8.5], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
    label: OxIconLabel('10', x: 12.5, baseline: 15.4, size: 7.5),
  ),
  fwd(
    'fwd',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 20, 12, 2, 20.006, 15.81, 17.324, 19.096, 13.59, 19.854, 2, 9.856, 20.611, 6.106, 18.629, 4.627, 15.118, 2, 3.148, 11.606, 4.352, 7.539, 7.503, 5.397, 2, 10.654, 3.255, 14.879, 3.633, 17.6, 6.3, 1, 20, 8.5], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 20, 3.5, 1, 20, 8.5, 1, 15, 8.5], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
    label: OxIconLabel('10', x: 11.5, baseline: 15.4, size: 7.5),
  ),
  epg(
    'epg',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 5.5, 4, 1, 18.5, 4, 2, 19.88, 4, 21, 5.12, 21, 6.5, 1, 21, 17.5, 2, 21, 18.88, 19.88, 20, 18.5, 20, 1, 5.5, 20, 2, 4.12, 20, 3, 18.88, 3, 17.5, 1, 3, 6.5, 2, 3, 5.12, 4.12, 4, 5.5, 4, 3], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 3, 9, 1, 21, 9, 0, 8, 9, 1, 8, 20, 0, 8, 14.5, 1, 21, 14.5, 0, 14, 9, 1, 14, 14.5], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
  ),
  edit(
    'edit',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 4, 20, 1, 8, 20, 1, 19, 9, 2, 20.104, 7.895, 20.104, 6.105, 19, 5, 2, 17.895, 3.896, 16.105, 3.896, 15, 5, 1, 4, 16, 3], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 13.5, 6.5, 1, 17.5, 10.5], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
  ),
  trash(
    'trash',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 4, 7, 1, 20, 7, 0, 10, 11, 1, 10, 17, 0, 14, 11, 1, 14, 17, 0, 6, 7, 1, 7, 19, 2, 7, 20.105, 7.895, 21, 9, 21, 1, 15, 21, 2, 16.105, 21, 17, 20.105, 17, 19, 1, 18, 7, 0, 9, 7, 1, 9, 4, 1, 15, 4, 1, 15, 7], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
  ),
  wifiOff(
    'wifi-off',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 2, 8.5, 2, 3.454, 7.183, 5.153, 6.163, 7, 5.5, 0, 22, 8.5, 2, 19.247, 6.047, 15.687, 4.695, 12, 4.7, 0, 5, 12.5, 2, 6.146, 11.468, 7.515, 10.715, 9, 10.3, 0, 19, 12.5, 2, 18.282, 11.853, 17.473, 11.315, 16.6, 10.9, 0, 8.5, 16, 2, 10.444, 14.094, 13.556, 14.094, 15.5, 16, 0, 12, 20, 1, 12.01, 20, 0, 3, 3, 1, 21, 21], width: 1.8, cap: StrokeCap.round),
    ],
  ),
  server(
    'server',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 5.5, 4, 1, 18.5, 4, 2, 19.604, 4, 20.5, 4.896, 20.5, 6, 1, 20.5, 9, 2, 20.5, 10.104, 19.604, 11, 18.5, 11, 1, 5.5, 11, 2, 4.396, 11, 3.5, 10.104, 3.5, 9, 1, 3.5, 6, 2, 3.5, 4.896, 4.396, 4, 5.5, 4, 3], width: 1.8, cap: StrokeCap.round),
      OxIconOp.stroke(<double>[0, 5.5, 13, 1, 18.5, 13, 2, 19.604, 13, 20.5, 13.896, 20.5, 15, 1, 20.5, 18, 2, 20.5, 19.104, 19.604, 20, 18.5, 20, 1, 5.5, 20, 2, 4.396, 20, 3.5, 19.104, 3.5, 18, 1, 3.5, 15, 2, 3.5, 13.896, 4.396, 13, 5.5, 13, 3], width: 1.8, cap: StrokeCap.round),
      OxIconOp.stroke(<double>[0, 7, 7.5, 1, 7.01, 7.5, 0, 7, 16.5, 1, 7.01, 16.5, 0, 11, 7.5, 1, 17, 7.5, 0, 11, 16.5, 1, 17, 16.5], width: 1.8, cap: StrokeCap.round),
    ],
  ),
  alert(
    'alert',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 12, 3.5, 1, 2.5, 20, 1, 21.5, 20, 3], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 12, 10, 1, 12, 14.5, 0, 12, 17.3, 1, 12.01, 17.3], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
  ),
  refresh(
    'refresh',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 20, 12, 2, 19.959, 15.814, 17.231, 19.069, 13.483, 19.775, 2, 9.735, 20.482, 6.009, 18.444, 4.582, 14.907, 2, 3.154, 11.37, 4.423, 7.318, 7.612, 5.225, 2, 10.801, 3.133, 15.023, 3.583, 17.7, 6.3, 1, 20, 8.5], width: 1.9, cap: StrokeCap.round, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 20, 3.5, 1, 20, 8.5, 1, 15, 8.5], width: 1.9, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
  ),
  link(
    'link',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 10, 14, 2, 10.752, 14.763, 11.779, 15.193, 12.85, 15.193, 2, 13.921, 15.193, 14.948, 14.763, 15.7, 14, 1, 18.7, 11, 2, 20.274, 9.426, 20.274, 6.874, 18.7, 5.3, 2, 17.126, 3.726, 14.574, 3.726, 13, 5.3, 1, 12, 6.3], width: 1.8, cap: StrokeCap.round),
      OxIconOp.stroke(<double>[0, 14, 10, 2, 13.248, 9.237, 12.221, 8.807, 11.15, 8.807, 2, 10.079, 8.807, 9.052, 9.237, 8.3, 10, 1, 5.3, 13, 2, 3.726, 14.574, 3.726, 17.126, 5.3, 18.7, 2, 6.874, 20.274, 9.426, 20.274, 11, 18.7, 1, 12, 17.7], width: 1.8, cap: StrokeCap.round),
    ],
  ),
  file(
    'file',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 14, 3, 1, 7, 3, 2, 5.895, 3, 5, 3.895, 5, 5, 1, 5, 19, 2, 5, 20.105, 5.895, 21, 7, 21, 1, 17, 21, 2, 18.105, 21, 19, 20.105, 19, 19, 1, 19, 8, 3], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 14, 3, 1, 14, 8, 1, 19, 8, 0, 9, 13, 1, 15, 13, 0, 9, 17, 1, 13, 17], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
  ),
  upload(
    'upload',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 12, 15, 1, 12, 3, 0, 7.5, 7.5, 1, 12, 3, 1, 16.5, 7.5], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 5, 15, 1, 5, 19, 2, 5, 20.105, 5.895, 21, 7, 21, 1, 17, 21, 2, 18.105, 21, 19, 20.105, 19, 19, 1, 19, 15], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
  ),
  key(
    'key',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 8, 11, 2, 10.208, 11, 12, 12.792, 12, 15, 2, 12, 17.208, 10.208, 19, 8, 19, 2, 5.792, 19, 4, 17.208, 4, 15, 2, 4, 12.792, 5.792, 11, 8, 11, 3], width: 1.8, cap: StrokeCap.round),
      OxIconOp.stroke(<double>[0, 11, 12, 1, 20, 3, 0, 17, 6, 1, 20, 9, 0, 14.5, 8.5, 1, 16.5, 10.5], width: 1.8, cap: StrokeCap.round),
    ],
  ),
  shield(
    'shield',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 12, 3, 1, 4.5, 6, 1, 4.5, 11.5, 2, 4.5, 16.1, 7.7, 19.9, 12, 21, 2, 16.3, 19.9, 19.5, 16.1, 19.5, 11.5, 1, 19.5, 6, 3], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 9, 12, 1, 11, 14, 1, 15, 10], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
  ),
  palette(
    'palette',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 12, 3, 2, 7.029, 3, 3, 7.029, 3, 12, 2, 3, 16.971, 7.029, 21, 12, 21, 2, 13.2, 21, 13.8, 20.2, 13.8, 19.3, 2, 13.8, 18, 12.8, 17.7, 12.8, 16.6, 2, 12.8, 15.6, 13.6, 15, 14.6, 15, 1, 17, 15, 2, 19.209, 15, 21, 13.209, 21, 11, 2, 21, 6.5, 17, 3, 12, 3, 3], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 7.5, 9.9, 2, 8.107, 9.9, 8.6, 10.393, 8.6, 11, 2, 8.6, 11.607, 8.107, 12.1, 7.5, 12.1, 2, 6.893, 12.1, 6.4, 11.607, 6.4, 11, 2, 6.4, 10.393, 6.893, 9.9, 7.5, 9.9, 3], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 10.5, 5.9, 2, 11.107, 5.9, 11.6, 6.393, 11.6, 7, 2, 11.6, 7.607, 11.107, 8.1, 10.5, 8.1, 2, 9.893, 8.1, 9.4, 7.607, 9.4, 7, 2, 9.4, 6.393, 9.893, 5.9, 10.5, 5.9, 3], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 15.5, 6.4, 2, 16.107, 6.4, 16.6, 6.893, 16.6, 7.5, 2, 16.6, 8.107, 16.107, 8.6, 15.5, 8.6, 2, 14.893, 8.6, 14.4, 8.107, 14.4, 7.5, 2, 14.4, 6.893, 14.893, 6.4, 15.5, 6.4, 3], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
  ),
  database(
    'database',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 12, 3, 2, 16.139, 3, 19.5, 4.12, 19.5, 5.5, 2, 19.5, 6.88, 16.139, 8, 12, 8, 2, 7.861, 8, 4.5, 6.88, 4.5, 5.5, 2, 4.5, 4.12, 7.861, 3, 12, 3, 3], width: 1.8),
      OxIconOp.stroke(<double>[0, 4.5, 5.5, 1, 4.5, 18.5, 2, 4.5, 19.9, 7.9, 21, 12, 21, 2, 16.1, 21, 19.5, 19.9, 19.5, 18.5, 1, 19.5, 5.5, 0, 4.5, 12, 2, 4.5, 13.4, 7.9, 14.5, 12, 14.5, 2, 16.1, 14.5, 19.5, 13.4, 19.5, 12], width: 1.8),
    ],
  ),
  eye(
    'eye',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 2, 12, 2, 2, 12, 5.6, 5, 12, 5, 2, 18.4, 5, 22, 12, 22, 12, 2, 22, 12, 18.4, 19, 12, 19, 2, 5.6, 19, 2, 12, 2, 12, 3], width: 1.8),
      OxIconOp.stroke(<double>[0, 12, 9, 2, 13.656, 9, 15, 10.344, 15, 12, 2, 15, 13.656, 13.656, 15, 12, 15, 2, 10.344, 15, 9, 13.656, 9, 12, 2, 9, 10.344, 10.344, 9, 12, 9, 3], width: 1.8),
    ],
  ),
  eyeOff(
    'eye-off',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 10.6, 5.1, 2, 11.064, 5.034, 11.532, 5.001, 12, 5, 2, 18.4, 5, 22, 12, 22, 12, 2, 21.36, 13.152, 20.588, 14.226, 19.7, 15.2, 0, 6.6, 6.6, 2, 3.7, 8.4, 2, 12, 2, 12, 2, 2, 12, 5.6, 19, 12, 19, 2, 13.919, 19.012, 15.798, 18.456, 17.4, 17.4, 0, 3, 3, 1, 21, 21, 0, 9.9, 9.9, 2, 9.004, 11.094, 9.123, 12.766, 10.179, 13.821, 2, 11.234, 14.877, 12.906, 14.996, 14.1, 14.1], width: 1.8, cap: StrokeCap.round),
    ],
  ),
  grip(
    'grip',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 9, 6, 1, 9.01, 6, 0, 15, 6, 1, 15.01, 6, 0, 9, 12, 1, 9.01, 12, 0, 15, 12, 1, 15.01, 12, 0, 9, 18, 1, 9.01, 18, 0, 15, 18, 1, 15.01, 18], width: 3, cap: StrokeCap.round),
    ],
  ),
  more(
    'more',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 12, 5, 1, 12.01, 5, 0, 12, 12, 1, 12.01, 12, 0, 12, 19, 1, 12.01, 19], width: 3, cap: StrokeCap.round),
    ],
  ),
  trailer(
    'trailer',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 5.5, 5, 1, 18.5, 5, 2, 20.156, 5, 21.5, 6.344, 21.5, 8, 1, 21.5, 16, 2, 21.5, 17.656, 20.156, 19, 18.5, 19, 1, 5.5, 19, 2, 3.844, 19, 2.5, 17.656, 2.5, 16, 1, 2.5, 8, 2, 2.5, 6.344, 3.844, 5, 5.5, 5, 3], width: 1.8, join: StrokeJoin.round),
      OxIconOp.fill(<double>[0, 10, 9.2, 1, 15, 12, 1, 10, 14.8, 3]),
      OxIconOp.stroke(<double>[0, 10, 9.2, 1, 15, 12, 1, 10, 14.8, 3], width: 1.8, join: StrokeJoin.round),
    ],
  ),
  history(
    'history',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 3, 12, 2, 3.034, 16.292, 6.094, 19.962, 10.309, 20.768, 2, 14.525, 21.574, 18.723, 19.291, 20.338, 15.315, 2, 21.953, 11.339, 20.536, 6.776, 16.953, 4.414, 2, 13.37, 2.052, 8.618, 2.548, 5.6, 5.6, 1, 3, 8], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 3, 3, 1, 3, 8, 1, 8, 8, 0, 12, 7.5, 1, 12, 12, 1, 15, 14], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
  ),
  trending(
    'trending',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 3, 17, 1, 9, 11, 1, 13, 15, 1, 21, 7], width: 1.9, cap: StrokeCap.round, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 15, 7, 1, 21, 7, 1, 21, 13], width: 1.9, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
  ),
  logout(
    'logout',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 15, 4, 1, 18, 4, 2, 19.105, 4, 20, 4.895, 20, 6, 1, 20, 18, 2, 20, 19.105, 19.105, 20, 18, 20, 1, 15, 20, 0, 10, 17, 1, 5, 12, 1, 10, 7, 0, 5, 12, 1, 16, 12], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
  ),
  playlist(
    'playlist',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 3, 6, 1, 16, 6, 0, 3, 11, 1, 16, 11, 0, 3, 16, 1, 11, 16], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
      OxIconOp.fill(<double>[0, 16, 14, 1, 16, 20, 1, 21, 17, 3]),
      OxIconOp.stroke(<double>[0, 16, 14, 1, 16, 20, 1, 21, 17, 3], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
  ),
  backspace(
    'backspace',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 8, 5, 1, 20, 5, 2, 20.552, 5, 21, 5.448, 21, 6, 1, 21, 18, 2, 21, 18.552, 20.552, 19, 20, 19, 1, 8, 19, 1, 2, 12, 3], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 11, 9, 1, 17, 15, 0, 17, 9, 1, 11, 15], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
    mirrorInRtl: true,
  ),
  cpu(
    'cpu',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 8, 6, 1, 16, 6, 2, 17.104, 6, 18, 6.896, 18, 8, 1, 18, 16, 2, 18, 17.104, 17.104, 18, 16, 18, 1, 8, 18, 2, 6.896, 18, 6, 17.104, 6, 16, 1, 6, 8, 2, 6, 6.896, 6.896, 6, 8, 6, 3], width: 1.8, cap: StrokeCap.round),
      OxIconOp.stroke(<double>[0, 9, 2.5, 1, 9, 6, 0, 15, 2.5, 1, 15, 6, 0, 9, 18, 1, 9, 21.5, 0, 15, 18, 1, 15, 21.5, 0, 2.5, 9, 1, 6, 9, 0, 2.5, 15, 1, 6, 15, 0, 18, 9, 1, 21.5, 9, 0, 18, 15, 1, 21.5, 15], width: 1.8, cap: StrokeCap.round),
    ],
  ),
  autoplay(
    'autoplay',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 12, 3, 2, 16.967, 3, 21, 7.033, 21, 12, 2, 21, 16.967, 16.967, 21, 12, 21, 2, 7.033, 21, 3, 16.967, 3, 12, 2, 3, 7.033, 7.033, 3, 12, 3, 3], width: 1.8, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 10, 8.5, 1, 15, 12, 1, 10, 15.5, 3], width: 1.8, join: StrokeJoin.round),
    ],
  ),
  translate(
    'translate',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 3, 5, 1, 13, 5, 0, 8, 3, 1, 8, 5, 0, 5, 5, 2, 5.5, 8.5, 8, 11.5, 11.5, 13, 0, 11, 5, 2, 10.5, 8.5, 8, 11.5, 4.5, 13], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
      OxIconOp.stroke(<double>[0, 12.5, 21, 1, 16.5, 11, 1, 20.5, 21, 0, 14, 17.5, 1, 19, 17.5], width: 1.8, cap: StrokeCap.round, join: StrokeJoin.round),
    ],
  ),
  signal(
    'signal',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 12, 10, 2, 13.104, 10, 14, 10.896, 14, 12, 2, 14, 13.104, 13.104, 14, 12, 14, 2, 10.896, 14, 10, 13.104, 10, 12, 2, 10, 10.896, 10.896, 10, 12, 10, 3], width: 1.8, cap: StrokeCap.round),
      OxIconOp.stroke(<double>[0, 7.8, 7.8, 2, 5.513, 10.133, 5.513, 13.867, 7.8, 16.2, 0, 16.2, 7.8, 2, 18.487, 10.133, 18.487, 13.867, 16.2, 16.2, 0, 4.9, 4.9, 2, 3.007, 6.778, 1.942, 9.334, 1.942, 12, 2, 1.942, 14.666, 3.007, 17.222, 4.9, 19.1, 0, 19.1, 4.9, 2, 20.993, 6.778, 22.058, 9.334, 22.058, 12, 2, 22.058, 14.666, 20.993, 17.222, 19.1, 19.1], width: 1.8, cap: StrokeCap.round),
    ],
  ),
  sliders(
    'sliders',
    <OxIconOp>[
      OxIconOp.stroke(<double>[0, 6, 3, 1, 6, 9, 0, 6, 13, 1, 6, 21, 0, 12, 3, 1, 12, 13, 0, 12, 17, 1, 12, 21, 0, 18, 3, 1, 18, 7, 0, 18, 11, 1, 18, 21], width: 1.8, cap: StrokeCap.round),
      OxIconOp.stroke(<double>[0, 3.5, 11, 1, 8.5, 11, 0, 9.5, 15, 1, 14.5, 15, 0, 15.5, 9, 1, 20.5, 9], width: 1.8, cap: StrokeCap.round),
    ],
  ),
  ;

  const OxIcons(this.id, this.ops, {this.mirrorInRtl = false, this.label});

  /// The CSS name without the `i-` prefix, e.g. `chev-r`.
  final String id;

  /// Draw operations in paint order.
  final List<OxIconOp> ops;

  /// Flip horizontally when the ambient [TextDirection] is RTL.
  final bool mirrorInRtl;

  /// Text drawn over the glyph (the "10" in rew/fwd).
  final OxIconLabel? label;
}
