// Generates the Orbix icon set from the design system stylesheet.
//
//   dart run tool/extract_icons.dart
//
// Reads  orbix-design-handoff/design/orbix.css  (`.i-*` rules, SVG data URIs)
// Writes lib/core/design/icons/ox_icons.data.dart  (the OxIcons enum)
//
// Each SVG is parsed with vector_graphics_compiler here, at generation time,
// and emitted as const path data. OxIcon then paints synchronously — no asset
// decode, so icons never pop in a frame late inside scrolling lists.
// Re-run whenever orbix.css changes; the output is checked in.
import 'dart:io';

import 'package:vector_graphics_compiler/vector_graphics_compiler.dart' as vg;

const _css = 'orbix-design-handoff/design/orbix.css';
const _out = 'lib/core/design/icons/ox_icons.data.dart';

/// Directional icons — the only ones flipped in RTL (`.flip` in the AR
/// screens). Media glyphs (play, rew, fwd, prev, next, volume…) never flip.
const _mirrorInRtl = {'back', 'backspace', 'chev-l', 'chev-r'};

final _rule = RegExp(r'''^\.i-([a-z0-9-]+)\{--i:url\("data:image/svg\+xml,(.*)"\)\}\s*$''');
final _text = RegExp(r'<text ([^>]*)>([^<]*)</text>');
final _attr = RegExp(r"""([a-z-]+)='([^']*)'""");

void main() {
  final b = StringBuffer();
  var count = 0;

  for (final line in File(_css).readAsLinesSync()) {
    final m = _rule.firstMatch(line);
    if (m == null) continue;
    final name = m.group(1)!;
    var svg = m.group(2)!;

    // SVG <text> asks for Arial and renders inconsistently; OxIcon draws the
    // label with a bundled font instead.
    String? label;
    final t = _text.firstMatch(svg);
    if (t != null) {
      final a = {for (final x in _attr.allMatches(t.group(1)!)) x.group(1)!: x.group(2)!};
      label = "label: OxIconLabel('${t.group(2)}', x: ${a['x']}, baseline: ${a['y']}, size: ${a['font-size']})";
      svg = svg.replaceFirst(t.group(0)!, '');
    }

    final ins = vg.parseWithoutOptimizers(svg, key: name, warningsAsErrors: true);
    if (ins.width != 24 || ins.height != 24) _fail(name, 'expected a 24×24 viewBox');

    final ops = <String>[];
    for (final cmd in ins.commands) {
      if (cmd.type != vg.DrawCommandType.path) _fail(name, 'unsupported draw command ${cmd.type}');
      final path = ins.paths[cmd.objectId!];
      final paint = ins.paints[cmd.paintId!];
      final data = _encode(name, path);
      final evenOdd = path.fillType == vg.PathFillType.evenOdd ? ', evenOdd: true' : '';
      if (paint.fill != null) {
        _checkBlack(name, paint.fill!.color);
        ops.add('OxIconOp.fill(<double>[$data]$evenOdd)');
      }
      final s = paint.stroke;
      if (s != null) {
        _checkBlack(name, s.color);
        ops.add('OxIconOp.stroke(<double>[$data], width: ${_n(s.width ?? 1)}'
            '${s.cap == null ? '' : ', cap: StrokeCap.${s.cap!.name}'}'
            '${s.join == null ? '' : ', join: StrokeJoin.${s.join!.name}'})');
      }
    }

    b.writeln('  ${_camel(name)}(');
    b.writeln("    '$name',");
    b.writeln('    <OxIconOp>[');
    for (final op in ops) {
      b.writeln('      $op,');
    }
    b.writeln('    ],');
    if (_mirrorInRtl.contains(name)) b.writeln('    mirrorInRtl: true,');
    if (label != null) b.writeln('    $label,');
    b.writeln('  ),');
    count++;
  }

  if (count == 0) _fail('-', 'no .i-* rules found in $_css');

  File(_out)
    ..createSync(recursive: true)
    ..writeAsStringSync('''
// GENERATED by tool/extract_icons.dart from $_css — do not edit.
//
// Path opcodes: 0 = moveTo(x, y), 1 = lineTo(x, y),
//               2 = cubicTo(x1, y1, x2, y2, x3, y3), 3 = close.
// ignore_for_file: lines_longer_than_80_chars

part of 'ox_icons.dart';

/// The Orbix icon set — $count icons on a 24 × 24 grid, from `.i-*` in orbix.css.
enum OxIcons {
$b  ;

  const OxIcons(this.id, this.ops, {this.mirrorInRtl = false, this.label});

  /// The CSS name without the `i-` prefix, e.g. `chev-r`.
  final String id;

  /// Draw operations in paint order.
  final List<OxIconOp> ops;

  /// Flip horizontally when the ambient [TextDirection] is RTL.
  final bool mirrorInRtl;

  /// Text drawn over the glyph (the "10" in rew/fwd).
  final OxIconLabel? label;
}
''');
  stdout.writeln('Generated $count icons → $_out');
}

String _encode(String icon, vg.Path path) {
  final out = <String>[];
  for (final c in path.commands) {
    switch (c) {
      case vg.MoveToCommand(:final x, :final y):
        out.addAll(['0', _n(x), _n(y)]);
      case vg.LineToCommand(:final x, :final y):
        out.addAll(['1', _n(x), _n(y)]);
      case vg.CubicToCommand(:final x1, :final y1, :final x2, :final y2, :final x3, :final y3):
        out.addAll(['2', _n(x1), _n(y1), _n(x2), _n(y2), _n(x3), _n(y3)]);
      case vg.CloseCommand():
        out.add('3');
      default:
        _fail(icon, 'unsupported path command ${c.runtimeType}');
    }
  }
  return out.join(', ');
}

/// Icons are single-colour masks (CSS `mask` + `currentColor`); anything other
/// than black in the source would be silently lost when tinting.
void _checkBlack(String icon, vg.Color c) {
  if (c.value != 0xFF000000) _fail(icon, 'non-black paint 0x${c.value.toRadixString(16)}');
}

String _n(double v) {
  final s = v.toStringAsFixed(3).replaceFirst(RegExp(r'0+$'), '').replaceFirst(RegExp(r'\.$'), '');
  return s == '-0' ? '0' : s;
}

String _camel(String kebab) {
  final p = kebab.split('-');
  return p.first + p.skip(1).map((s) => s[0].toUpperCase() + s.substring(1)).join();
}

Never _fail(String icon, String msg) {
  stderr.writeln('extract_icons: i-$icon: $msg');
  exit(1);
}
